import httpx
from bs4 import BeautifulSoup
from models import ResearchRequest, CompanyIntelligence, Signal

async def fetch_page_text(url: str) -> str:
    """Fetches a webpage and extracts its text."""
    try:
        async with httpx.AsyncClient() as client:
            response = await client.get(url, timeout=10.0)
            response.raise_for_status()
            
            soup = BeautifulSoup(response.text, 'html.parser')
            # Remove script and style elements
            for script in soup(["script", "style"]):
                script.extract()
                
            text = soup.get_text(separator=' ', strip=True)
            return text
    except Exception as e:
        print(f"Error fetching {url}: {e}")
        return ""

async def generate_company_intelligence(request: ResearchRequest) -> CompanyIntelligence:
    """
    Orchestrates the research process:
    1. Scrapes the company website and LinkedIn.
    2. Sends the scraped text to the Gemini API for reasoning and extraction.
    3. Returns a structured CompanyIntelligence profile.
    """
    
    # 1. Scrape content
    website_text = await fetch_page_text(str(request.company_website))
    
    # In a real implementation, you'd use a web search API (e.g. SERP API) 
    # to find additional recent news and press releases here.
    
    # 2. Mock Reasoning Layer (Gemini Integration Placeholder)
    # Since we are keeping this self-contained for now, we mock the Gemini extraction.
    print(f"Scraped {len(website_text)} characters from {request.company_website}")
    
    mock_signals = [
        Signal(
            finding=f"The company website ({request.company_website}) highlights digital transformation.",
            signal_type="fact",
            source_url=str(request.company_website),
            confidence="High"
        ),
        Signal(
            finding="They might struggle with legacy system integrations.",
            signal_type="hypothesis",
            source_url=str(request.company_website),
            confidence="Medium"
        )
    ]
    
    # 3. Construct the response
    return CompanyIntelligence(
        company_name="Acme Corp (Mocked)",
        industry="Technology (Mocked)",
        overview="Acme Corp is a fictional company generated by our self-contained mock reasoning layer. It demonstrates the expected structured output.",
        signals=mock_signals
    )
